name: Build and deploy package

on:
  release:
    types: [published]

jobs:
  deploy-package:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create Gem credentials
        env:
          GEM_HOST_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
      - name: Build package
        run: |
          gem build *.gemspec
      - name: Push to GitHub Package Registry
        env:
          OWNER: ${{ github.repository_owner }}
        run: |
          gem push *.gem --key github --host https://rubygems.pkg.github.com/${OWNER}
